services:

  mysql:
    image: mysql:8
    container_name: wildsight-mysql

    environment:
      MYSQL_DATABASE: wildsight_db
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

    networks:
      - wildsight-network


  backend:
    build:
      context: ./wildsight-backend/wildsight-backend
      dockerfile: Dockerfile

    image: wildsight-backend
    container_name: wildsight-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wildsight_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - backend-uploads:/app/uploads
      - "D:/projects/wildlife/datasets:/app/datasets"

    networks:
      - wildsight-network


  frontend:
    build:
      context: ./wildsight-ai-main/wildsight-ai-main
      dockerfile: Dockerfile

    image: wildsight-frontend
    container_name: wildsight-frontend

    ports:
      - "80:3000"

    depends_on:
      - backend

    networks:
      - wildsight-network


volumes:

  mysql-data:

  backend-uploads:


networks:

  wildsight-network:
    driver: bridge