version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wildlife_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildlife_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
      target: backend-dev
    container_name: wildlife_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wildlife_db
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wildlife_db
      - POSTGRES_PORT=5432
      - SECRET_KEY=supersecretjwtkeyforwildlifepopulationintelligence2026
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/workspace

volumes:
  pgdata:
