from fastapi import APIRouter, Depends
from app.api.deps import get_current_active_user
from app.models.user import User
from app.schemas.recommendations import RecommendationsResponse
from app.services.recommendation_service import recommendation_service

router = APIRouter()

@router.get("", response_model=RecommendationsResponse)
def get_conservation_recommendations(
    current_user: User = Depends(get_current_active_user)
):
    """
    Exposes policy guidelines generated by the AI conservation recommendation engine.
    """
    return recommendation_service.get_recommendations()
