package com.wildsight.backend.dto;

import com.wildsight.backend.entity.ReportStatus;
import jakarta.validation.constraints.*;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReportRequest {

    @NotNull(message = "Survey is required")
    private Long surveyId;

    @NotNull(message = "Generated by user is required")
    private Long generatedBy;

    @NotBlank(message = "Report title is required")
    @Size(min = 3, max = 200,
            message = "Report title must be between 3 and 200 characters")
    private String reportTitle;

    @NotBlank(message = "Report type is required")
    @Size(max = 100,
            message = "Report type cannot exceed 100 characters")
    private String reportType;

    @Size(max = 500,
            message = "Report path cannot exceed 500 characters")
    private String reportPath;

    @NotNull(message = "Report status is required")
    private ReportStatus reportStatus;
}