"""create ecosystem health history table

Revision ID: 5ddd288292da
Revises: d0260e26fea9
Create Date: 2026-07-30 10:25:58.498497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddd288292da'
down_revision: Union[str, Sequence[str], None] = 'd0260e26fea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystem_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('biodiversity_score', sa.Float(), nullable=False),
    sa.Column('population_score', sa.Float(), nullable=False),
    sa.Column('habitat_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecosystem_health_history_id'), 'ecosystem_health_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecosystem_health_history_id'), table_name='ecosystem_health_history')
    op.drop_table('ecosystem_health_history')
    # ### end Alembic commands ###
