"""add_is_resolved_to_notifications

Revision ID: 95e6f2ab9c54
Revises: 1ace36fe20f6
Create Date: 2026-08-18 12:10:07.278494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e6f2ab9c54'
down_revision: Union[str, None] = '1ace36fe20f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('notifications', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.execute("UPDATE notifications SET is_resolved = false")
    op.alter_column('notifications', 'is_resolved', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_resolved')
    # ### end Alembic commands ###
