"""Add AIAnalysis table

Revision ID: b894234cfe33
Revises: 44885077f026
Create Date: 2026-08-06 21:07:39.088934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b894234cfe33'
down_revision: Union[str, None] = '44885077f026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('image_completed', sa.Boolean(), nullable=False),
    sa.Column('audio_completed', sa.Boolean(), nullable=False),
    sa.Column('image_json', sa.JSON(), nullable=True),
    sa.Column('audio_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_observation_id'), 'ai_analyses', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_observation_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
