"""create wildlife observations table

Revision ID: d0260e26fea9
Revises: e8d9d3e53a53
Create Date: 2026-07-10 11:11:57.503857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0260e26fea9'
down_revision: Union[str, Sequence[str], None] = 'e8d9d3e53a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wildlife_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('protected_area_id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('animal_count', sa.Integer(), nullable=False),
    sa.Column('observation_type', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protected_area_id'], ['protected_areas.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wildlife_observations_id'), 'wildlife_observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wildlife_observations_id'), table_name='wildlife_observations')
    op.drop_table('wildlife_observations')
    # ### end Alembic commands ###
