/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWildlifeDashboardRouteImport } from './routes/_authenticated/wildlife-dashboard'
import { Route as AuthenticatedSurveysRouteImport } from './routes/_authenticated/surveys'
import { Route as AuthenticatedSpeciesIdentificationRouteImport } from './routes/_authenticated/species-identification'
import { Route as AuthenticatedSpeciesRouteImport } from './routes/_authenticated/species'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProtectedAreasRouteImport } from './routes/_authenticated/protected-areas'
import { Route as AuthenticatedPopulationIntelligenceRouteImport } from './routes/_authenticated/population-intelligence'
import { Route as AuthenticatedPopulationRouteImport } from './routes/_authenticated/population'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMapsRouteImport } from './routes/_authenticated/maps'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedImageAnalysisRouteImport } from './routes/_authenticated/image-analysis'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedHabitatRouteImport } from './routes/_authenticated/habitat'
import { Route as AuthenticatedEcosystemHealthRouteImport } from './routes/_authenticated/ecosystem-health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConservationIntelligenceRouteImport } from './routes/_authenticated/conservation-intelligence'
import { Route as AuthenticatedConservationRouteImport } from './routes/_authenticated/conservation'
import { Route as AuthenticatedBiodiversityRouteImport } from './routes/_authenticated/biodiversity'
import { Route as AuthenticatedAudioAnalysisRouteImport } from './routes/_authenticated/audio-analysis'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAddObservationRouteImport } from './routes/_authenticated/add-observation'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWildlifeDashboardRoute =
  AuthenticatedWildlifeDashboardRouteImport.update({
    id: '/wildlife-dashboard',
    path: '/wildlife-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSurveysRoute = AuthenticatedSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpeciesIdentificationRoute =
  AuthenticatedSpeciesIdentificationRouteImport.update({
    id: '/species-identification',
    path: '/species-identification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpeciesRoute = AuthenticatedSpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtectedAreasRoute =
  AuthenticatedProtectedAreasRouteImport.update({
    id: '/protected-areas',
    path: '/protected-areas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPopulationIntelligenceRoute =
  AuthenticatedPopulationIntelligenceRouteImport.update({
    id: '/population-intelligence',
    path: '/population-intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPopulationRoute = AuthenticatedPopulationRouteImport.update({
  id: '/population',
  path: '/population',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapsRoute = AuthenticatedMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImageAnalysisRoute =
  AuthenticatedImageAnalysisRouteImport.update({
    id: '/image-analysis',
    path: '/image-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitatRoute = AuthenticatedHabitatRouteImport.update({
  id: '/habitat',
  path: '/habitat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEcosystemHealthRoute =
  AuthenticatedEcosystemHealthRouteImport.update({
    id: '/ecosystem-health',
    path: '/ecosystem-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConservationIntelligenceRoute =
  AuthenticatedConservationIntelligenceRouteImport.update({
    id: '/conservation-intelligence',
    path: '/conservation-intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConservationRoute =
  AuthenticatedConservationRouteImport.update({
    id: '/conservation',
    path: '/conservation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBiodiversityRoute =
  AuthenticatedBiodiversityRouteImport.update({
    id: '/biodiversity',
    path: '/biodiversity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAudioAnalysisRoute =
  AuthenticatedAudioAnalysisRouteImport.update({
    id: '/audio-analysis',
    path: '/audio-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddObservationRoute =
  AuthenticatedAddObservationRouteImport.update({
    id: '/add-observation',
    path: '/add-observation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-observation': typeof AuthenticatedAddObservationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audio-analysis': typeof AuthenticatedAudioAnalysisRoute
  '/biodiversity': typeof AuthenticatedBiodiversityRoute
  '/conservation': typeof AuthenticatedConservationRoute
  '/conservation-intelligence': typeof AuthenticatedConservationIntelligenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ecosystem-health': typeof AuthenticatedEcosystemHealthRoute
  '/habitat': typeof AuthenticatedHabitatRoute
  '/health': typeof AuthenticatedHealthRoute
  '/image-analysis': typeof AuthenticatedImageAnalysisRoute
  '/map': typeof AuthenticatedMapRoute
  '/maps': typeof AuthenticatedMapsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/population': typeof AuthenticatedPopulationRoute
  '/population-intelligence': typeof AuthenticatedPopulationIntelligenceRoute
  '/protected-areas': typeof AuthenticatedProtectedAreasRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/species': typeof AuthenticatedSpeciesRoute
  '/species-identification': typeof AuthenticatedSpeciesIdentificationRoute
  '/surveys': typeof AuthenticatedSurveysRoute
  '/wildlife-dashboard': typeof AuthenticatedWildlifeDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-observation': typeof AuthenticatedAddObservationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audio-analysis': typeof AuthenticatedAudioAnalysisRoute
  '/biodiversity': typeof AuthenticatedBiodiversityRoute
  '/conservation': typeof AuthenticatedConservationRoute
  '/conservation-intelligence': typeof AuthenticatedConservationIntelligenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ecosystem-health': typeof AuthenticatedEcosystemHealthRoute
  '/habitat': typeof AuthenticatedHabitatRoute
  '/health': typeof AuthenticatedHealthRoute
  '/image-analysis': typeof AuthenticatedImageAnalysisRoute
  '/map': typeof AuthenticatedMapRoute
  '/maps': typeof AuthenticatedMapsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/population': typeof AuthenticatedPopulationRoute
  '/population-intelligence': typeof AuthenticatedPopulationIntelligenceRoute
  '/protected-areas': typeof AuthenticatedProtectedAreasRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/species': typeof AuthenticatedSpeciesRoute
  '/species-identification': typeof AuthenticatedSpeciesIdentificationRoute
  '/surveys': typeof AuthenticatedSurveysRoute
  '/wildlife-dashboard': typeof AuthenticatedWildlifeDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add-observation': typeof AuthenticatedAddObservationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audio-analysis': typeof AuthenticatedAudioAnalysisRoute
  '/_authenticated/biodiversity': typeof AuthenticatedBiodiversityRoute
  '/_authenticated/conservation': typeof AuthenticatedConservationRoute
  '/_authenticated/conservation-intelligence': typeof AuthenticatedConservationIntelligenceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ecosystem-health': typeof AuthenticatedEcosystemHealthRoute
  '/_authenticated/habitat': typeof AuthenticatedHabitatRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/image-analysis': typeof AuthenticatedImageAnalysisRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/maps': typeof AuthenticatedMapsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/population': typeof AuthenticatedPopulationRoute
  '/_authenticated/population-intelligence': typeof AuthenticatedPopulationIntelligenceRoute
  '/_authenticated/protected-areas': typeof AuthenticatedProtectedAreasRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/species': typeof AuthenticatedSpeciesRoute
  '/_authenticated/species-identification': typeof AuthenticatedSpeciesIdentificationRoute
  '/_authenticated/surveys': typeof AuthenticatedSurveysRoute
  '/_authenticated/wildlife-dashboard': typeof AuthenticatedWildlifeDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add-observation'
    | '/admin'
    | '/audio-analysis'
    | '/biodiversity'
    | '/conservation'
    | '/conservation-intelligence'
    | '/dashboard'
    | '/ecosystem-health'
    | '/habitat'
    | '/health'
    | '/image-analysis'
    | '/map'
    | '/maps'
    | '/notifications'
    | '/population'
    | '/population-intelligence'
    | '/protected-areas'
    | '/reports'
    | '/species'
    | '/species-identification'
    | '/surveys'
    | '/wildlife-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add-observation'
    | '/admin'
    | '/audio-analysis'
    | '/biodiversity'
    | '/conservation'
    | '/conservation-intelligence'
    | '/dashboard'
    | '/ecosystem-health'
    | '/habitat'
    | '/health'
    | '/image-analysis'
    | '/map'
    | '/maps'
    | '/notifications'
    | '/population'
    | '/population-intelligence'
    | '/protected-areas'
    | '/reports'
    | '/species'
    | '/species-identification'
    | '/surveys'
    | '/wildlife-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add-observation'
    | '/_authenticated/admin'
    | '/_authenticated/audio-analysis'
    | '/_authenticated/biodiversity'
    | '/_authenticated/conservation'
    | '/_authenticated/conservation-intelligence'
    | '/_authenticated/dashboard'
    | '/_authenticated/ecosystem-health'
    | '/_authenticated/habitat'
    | '/_authenticated/health'
    | '/_authenticated/image-analysis'
    | '/_authenticated/map'
    | '/_authenticated/maps'
    | '/_authenticated/notifications'
    | '/_authenticated/population'
    | '/_authenticated/population-intelligence'
    | '/_authenticated/protected-areas'
    | '/_authenticated/reports'
    | '/_authenticated/species'
    | '/_authenticated/species-identification'
    | '/_authenticated/surveys'
    | '/_authenticated/wildlife-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wildlife-dashboard': {
      id: '/_authenticated/wildlife-dashboard'
      path: '/wildlife-dashboard'
      fullPath: '/wildlife-dashboard'
      preLoaderRoute: typeof AuthenticatedWildlifeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/surveys': {
      id: '/_authenticated/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AuthenticatedSurveysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/species-identification': {
      id: '/_authenticated/species-identification'
      path: '/species-identification'
      fullPath: '/species-identification'
      preLoaderRoute: typeof AuthenticatedSpeciesIdentificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/species': {
      id: '/_authenticated/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof AuthenticatedSpeciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protected-areas': {
      id: '/_authenticated/protected-areas'
      path: '/protected-areas'
      fullPath: '/protected-areas'
      preLoaderRoute: typeof AuthenticatedProtectedAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/population-intelligence': {
      id: '/_authenticated/population-intelligence'
      path: '/population-intelligence'
      fullPath: '/population-intelligence'
      preLoaderRoute: typeof AuthenticatedPopulationIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/population': {
      id: '/_authenticated/population'
      path: '/population'
      fullPath: '/population'
      preLoaderRoute: typeof AuthenticatedPopulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maps': {
      id: '/_authenticated/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof AuthenticatedMapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/image-analysis': {
      id: '/_authenticated/image-analysis'
      path: '/image-analysis'
      fullPath: '/image-analysis'
      preLoaderRoute: typeof AuthenticatedImageAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habitat': {
      id: '/_authenticated/habitat'
      path: '/habitat'
      fullPath: '/habitat'
      preLoaderRoute: typeof AuthenticatedHabitatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ecosystem-health': {
      id: '/_authenticated/ecosystem-health'
      path: '/ecosystem-health'
      fullPath: '/ecosystem-health'
      preLoaderRoute: typeof AuthenticatedEcosystemHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conservation-intelligence': {
      id: '/_authenticated/conservation-intelligence'
      path: '/conservation-intelligence'
      fullPath: '/conservation-intelligence'
      preLoaderRoute: typeof AuthenticatedConservationIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conservation': {
      id: '/_authenticated/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof AuthenticatedConservationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biodiversity': {
      id: '/_authenticated/biodiversity'
      path: '/biodiversity'
      fullPath: '/biodiversity'
      preLoaderRoute: typeof AuthenticatedBiodiversityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audio-analysis': {
      id: '/_authenticated/audio-analysis'
      path: '/audio-analysis'
      fullPath: '/audio-analysis'
      preLoaderRoute: typeof AuthenticatedAudioAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-observation': {
      id: '/_authenticated/add-observation'
      path: '/add-observation'
      fullPath: '/add-observation'
      preLoaderRoute: typeof AuthenticatedAddObservationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddObservationRoute: typeof AuthenticatedAddObservationRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAudioAnalysisRoute: typeof AuthenticatedAudioAnalysisRoute
  AuthenticatedBiodiversityRoute: typeof AuthenticatedBiodiversityRoute
  AuthenticatedConservationRoute: typeof AuthenticatedConservationRoute
  AuthenticatedConservationIntelligenceRoute: typeof AuthenticatedConservationIntelligenceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEcosystemHealthRoute: typeof AuthenticatedEcosystemHealthRoute
  AuthenticatedHabitatRoute: typeof AuthenticatedHabitatRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedImageAnalysisRoute: typeof AuthenticatedImageAnalysisRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMapsRoute: typeof AuthenticatedMapsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPopulationRoute: typeof AuthenticatedPopulationRoute
  AuthenticatedPopulationIntelligenceRoute: typeof AuthenticatedPopulationIntelligenceRoute
  AuthenticatedProtectedAreasRoute: typeof AuthenticatedProtectedAreasRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSpeciesRoute: typeof AuthenticatedSpeciesRoute
  AuthenticatedSpeciesIdentificationRoute: typeof AuthenticatedSpeciesIdentificationRoute
  AuthenticatedSurveysRoute: typeof AuthenticatedSurveysRoute
  AuthenticatedWildlifeDashboardRoute: typeof AuthenticatedWildlifeDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddObservationRoute: AuthenticatedAddObservationRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAudioAnalysisRoute: AuthenticatedAudioAnalysisRoute,
  AuthenticatedBiodiversityRoute: AuthenticatedBiodiversityRoute,
  AuthenticatedConservationRoute: AuthenticatedConservationRoute,
  AuthenticatedConservationIntelligenceRoute:
    AuthenticatedConservationIntelligenceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEcosystemHealthRoute: AuthenticatedEcosystemHealthRoute,
  AuthenticatedHabitatRoute: AuthenticatedHabitatRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedImageAnalysisRoute: AuthenticatedImageAnalysisRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMapsRoute: AuthenticatedMapsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPopulationRoute: AuthenticatedPopulationRoute,
  AuthenticatedPopulationIntelligenceRoute:
    AuthenticatedPopulationIntelligenceRoute,
  AuthenticatedProtectedAreasRoute: AuthenticatedProtectedAreasRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSpeciesRoute: AuthenticatedSpeciesRoute,
  AuthenticatedSpeciesIdentificationRoute:
    AuthenticatedSpeciesIdentificationRoute,
  AuthenticatedSurveysRoute: AuthenticatedSurveysRoute,
  AuthenticatedWildlifeDashboardRoute: AuthenticatedWildlifeDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
