/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProtectedAreasRouteImport } from './routes/protected-areas'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as HabitatHealthRouteImport } from './routes/habitat-health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AiDetectionsRouteImport } from './routes/ai-detections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysIdRouteImport } from './routes/surveys.$id'
import { Route as ApiPublicAiPopulationEstimationRouteImport } from './routes/api/public/ai/population-estimation'
import { Route as ApiPublicAiImageDetectionRouteImport } from './routes/api/public/ai/image-detection'
import { Route as ApiPublicAiAudioDetectionRouteImport } from './routes/api/public/ai/audio-detection'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAreasRoute = ProtectedAreasRouteImport.update({
  id: '/protected-areas',
  path: '/protected-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitatHealthRoute = HabitatHealthRouteImport.update({
  id: '/habitat-health',
  path: '/habitat-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectionsRoute = AiDetectionsRouteImport.update({
  id: '/ai-detections',
  path: '/ai-detections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIdRoute = SurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SurveysRoute,
} as any)
const ApiPublicAiPopulationEstimationRoute =
  ApiPublicAiPopulationEstimationRouteImport.update({
    id: '/api/public/ai/population-estimation',
    path: '/api/public/ai/population-estimation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiImageDetectionRoute =
  ApiPublicAiImageDetectionRouteImport.update({
    id: '/api/public/ai/image-detection',
    path: '/api/public/ai/image-detection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiAudioDetectionRoute =
  ApiPublicAiAudioDetectionRouteImport.update({
    id: '/api/public/ai/audio-detection',
    path: '/api/public/ai/audio-detection',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-detections': typeof AiDetectionsRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/habitat-health': typeof HabitatHealthRoute
  '/images': typeof ImagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/protected-areas': typeof ProtectedAreasRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/species': typeof SpeciesRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/users': typeof UsersRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/api/public/ai/audio-detection': typeof ApiPublicAiAudioDetectionRoute
  '/api/public/ai/image-detection': typeof ApiPublicAiImageDetectionRoute
  '/api/public/ai/population-estimation': typeof ApiPublicAiPopulationEstimationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-detections': typeof AiDetectionsRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/habitat-health': typeof HabitatHealthRoute
  '/images': typeof ImagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/protected-areas': typeof ProtectedAreasRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/species': typeof SpeciesRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/users': typeof UsersRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/api/public/ai/audio-detection': typeof ApiPublicAiAudioDetectionRoute
  '/api/public/ai/image-detection': typeof ApiPublicAiImageDetectionRoute
  '/api/public/ai/population-estimation': typeof ApiPublicAiPopulationEstimationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-detections': typeof AiDetectionsRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/habitat-health': typeof HabitatHealthRoute
  '/images': typeof ImagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/protected-areas': typeof ProtectedAreasRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/species': typeof SpeciesRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/users': typeof UsersRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/api/public/ai/audio-detection': typeof ApiPublicAiAudioDetectionRoute
  '/api/public/ai/image-detection': typeof ApiPublicAiImageDetectionRoute
  '/api/public/ai/population-estimation': typeof ApiPublicAiPopulationEstimationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-detections'
    | '/audio'
    | '/auth'
    | '/dashboard'
    | '/habitat-health'
    | '/images'
    | '/notifications'
    | '/profile'
    | '/protected-areas'
    | '/reports'
    | '/sitemap.xml'
    | '/species'
    | '/surveys'
    | '/users'
    | '/surveys/$id'
    | '/api/public/ai/audio-detection'
    | '/api/public/ai/image-detection'
    | '/api/public/ai/population-estimation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-detections'
    | '/audio'
    | '/auth'
    | '/dashboard'
    | '/habitat-health'
    | '/images'
    | '/notifications'
    | '/profile'
    | '/protected-areas'
    | '/reports'
    | '/sitemap.xml'
    | '/species'
    | '/surveys'
    | '/users'
    | '/surveys/$id'
    | '/api/public/ai/audio-detection'
    | '/api/public/ai/image-detection'
    | '/api/public/ai/population-estimation'
  id:
    | '__root__'
    | '/'
    | '/ai-detections'
    | '/audio'
    | '/auth'
    | '/dashboard'
    | '/habitat-health'
    | '/images'
    | '/notifications'
    | '/profile'
    | '/protected-areas'
    | '/reports'
    | '/sitemap.xml'
    | '/species'
    | '/surveys'
    | '/users'
    | '/surveys/$id'
    | '/api/public/ai/audio-detection'
    | '/api/public/ai/image-detection'
    | '/api/public/ai/population-estimation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDetectionsRoute: typeof AiDetectionsRoute
  AudioRoute: typeof AudioRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HabitatHealthRoute: typeof HabitatHealthRoute
  ImagesRoute: typeof ImagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProtectedAreasRoute: typeof ProtectedAreasRoute
  ReportsRoute: typeof ReportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeciesRoute: typeof SpeciesRoute
  SurveysRoute: typeof SurveysRouteWithChildren
  UsersRoute: typeof UsersRoute
  ApiPublicAiAudioDetectionRoute: typeof ApiPublicAiAudioDetectionRoute
  ApiPublicAiImageDetectionRoute: typeof ApiPublicAiImageDetectionRoute
  ApiPublicAiPopulationEstimationRoute: typeof ApiPublicAiPopulationEstimationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected-areas': {
      id: '/protected-areas'
      path: '/protected-areas'
      fullPath: '/protected-areas'
      preLoaderRoute: typeof ProtectedAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitat-health': {
      id: '/habitat-health'
      path: '/habitat-health'
      fullPath: '/habitat-health'
      preLoaderRoute: typeof HabitatHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detections': {
      id: '/ai-detections'
      path: '/ai-detections'
      fullPath: '/ai-detections'
      preLoaderRoute: typeof AiDetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$id': {
      id: '/surveys/$id'
      path: '/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof SurveysIdRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/api/public/ai/population-estimation': {
      id: '/api/public/ai/population-estimation'
      path: '/api/public/ai/population-estimation'
      fullPath: '/api/public/ai/population-estimation'
      preLoaderRoute: typeof ApiPublicAiPopulationEstimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/image-detection': {
      id: '/api/public/ai/image-detection'
      path: '/api/public/ai/image-detection'
      fullPath: '/api/public/ai/image-detection'
      preLoaderRoute: typeof ApiPublicAiImageDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/audio-detection': {
      id: '/api/public/ai/audio-detection'
      path: '/api/public/ai/audio-detection'
      fullPath: '/api/public/ai/audio-detection'
      preLoaderRoute: typeof ApiPublicAiAudioDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SurveysRouteChildren {
  SurveysIdRoute: typeof SurveysIdRoute
}

const SurveysRouteChildren: SurveysRouteChildren = {
  SurveysIdRoute: SurveysIdRoute,
}

const SurveysRouteWithChildren =
  SurveysRoute._addFileChildren(SurveysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDetectionsRoute: AiDetectionsRoute,
  AudioRoute: AudioRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HabitatHealthRoute: HabitatHealthRoute,
  ImagesRoute: ImagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProtectedAreasRoute: ProtectedAreasRoute,
  ReportsRoute: ReportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeciesRoute: SpeciesRoute,
  SurveysRoute: SurveysRouteWithChildren,
  UsersRoute: UsersRoute,
  ApiPublicAiAudioDetectionRoute: ApiPublicAiAudioDetectionRoute,
  ApiPublicAiImageDetectionRoute: ApiPublicAiImageDetectionRoute,
  ApiPublicAiPopulationEstimationRoute: ApiPublicAiPopulationEstimationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
