# User Roles
ROLE_ADMIN = "Administrator"
ROLE_RESEARCHER = "Wildlife Researcher"
ROLE_OFFICER = "Conservation Officer"
ROLE_FOREST_DEPT = "Forest Department Officer"

ALL_ROLES = [ROLE_ADMIN, ROLE_RESEARCHER, ROLE_OFFICER, ROLE_FOREST_DEPT]

# Pagination defaults
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Device statuses
STATUS_ACTIVE = "Active"
STATUS_INACTIVE = "Inactive"
STATUS_MAINTENANCE = "Maintenance"

DEVICE_STATUSES = [STATUS_ACTIVE, STATUS_INACTIVE, STATUS_MAINTENANCE]

# Survey statuses
SURVEY_STATUS_PLANNED = "Planned"
SURVEY_STATUS_ACTIVE = "Active"
SURVEY_STATUS_COMPLETED = "Completed"

SURVEY_STATUSES = [SURVEY_STATUS_PLANNED, SURVEY_STATUS_ACTIVE, SURVEY_STATUS_COMPLETED]
